FROM node:20-alpine3.19

WORKDIR "/app"

RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm
# 只有package.josn 有变化时 才执行 pnpm install
COPY package.json .

RUN apk add --no-cache git && pnpm install

COPY . .
CMD pnpm dev