name: CI/CD Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Docker image
        run: docker build -t bamboo-sword:test -f Dockerfile.dev .

      - name: Run tests
        run: docker run bamboo-sword:test pnpm test -- --coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bamboo-sword
          environment_name: Bamboo-sword-env
          existing_bucket_name: elasticbeanstalk-us-east-2-767397776477
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
